export const STREAM_HEARTBEAT_INTERVAL_MS = 30_000;
export const STREAM_HEARTBEAT_JITTER_MS = 10_000;
export const STREAM_LIVENESS_THRESHOLD_MS = STREAM_HEARTBEAT_INTERVAL_MS + STREAM_HEARTBEAT_JITTER_MS;
