name: Test and lint
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  check:
    name: Test and lint
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install
      - name: Build
        run: |
          bun run build
      - name: Publish package for testing branch
        run: npx pkg-pr-new publish || echo "Have you set up pkg-pr-new for this repo?"
      - name: Test
        run: |
          bun run test
          bun run typecheck
          bun run lint
